#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input())
  
    binary = bin(n)[2:]
    substring = max(binary.split('0'))
    print( len(substring))
